### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by breponte** [breponte/sp23-cse110-lab3#2]
Add CSS Styling to index.html from Lab 2.

**Comment by k-deepak04** [comment]
@breponte i would like to contribute in this.

**Comment by k-deepak04** [comment]
#5 @breponte check this PR.

**Comment by breponte** [comment]
@k-deepak04 Sorry, man. This is for a class so I cannot take your contributions. Thanks, though.

**Comment by k-deepak04** [comment]
@breponte no problem man. 
Thanks for letting me know :)
